In [6]:
import random
import torch
import numpy as np

In [69]:
from microservice.models.model_b import SimpleNN
from models.train_utils_nn import train_and_extract
from models.utils import load_default_data, calculate_expenses
from microservice.features import extract_users_data, prepare_data_for_predict
from sklearn.metrics import roc_auc_score as roc
from microservice.models.model_b import NeuralNetworkRegressor

In [8]:
seed = 213769420
torch.cuda.manual_seed_all(seed)
torch.manual_seed(seed)
np.random.seed(seed)
random.seed(seed)

In [103]:
train, test, products, users, deliveries = load_default_data()
targets = calculate_expenses(test, products, users)

In [104]:
targets['expenses'] = targets['expenses'].apply(lambda b: 1 if b > 5000 else 0)

In [105]:
targets

user_id  expenses
0        102         0
1        103         0
2        104         0
3        105         0
4        106         0
..       ...       ...
195      297         0
196      298         0
197      299         0
198      300         0
199      301         0

[200 rows x 2 columns]

In [106]:
some_net = NeuralNetworkRegressor()

In [107]:
train_and_extract(some_net, train, users, products, targets)

Epoch 0 loss 0.103
Epoch 1 loss 0.0991
Epoch 2 loss 0.102
Epoch 3 loss 0.0776
Epoch 4 loss 0.173
Epoch 5 loss 0.0468
Epoch 6 loss 0.0566
Epoch 7 loss 0.116
Epoch 8 loss 0.0563
Epoch 9 loss 0.0525
Epoch 10 loss 0.105
Epoch 11 loss 0.0783
Epoch 12 loss 0.0788
Epoch 13 loss 0.0509
Epoch 14 loss 0.0679
Epoch 15 loss 0.0553
Epoch 16 loss 0.0637
Epoch 17 loss 0.0672
Epoch 18 loss 0.0854
Epoch 19 loss 0.0621
Epoch 20 loss 0.0473
Epoch 21 loss 0.0628
Epoch 22 loss 0.0492
Epoch 23 loss 0.0704
Epoch 24 loss 0.0662
Epoch 25 loss 0.0538
Epoch 26 loss 0.171
Epoch 27 loss 0.043
Epoch 28 loss 0.0364
Epoch 29 loss 0.0453
Epoch 30 loss 0.0552
Epoch 31 loss 0.0502
Epoch 32 loss 0.0514
Epoch 33 loss 0.0561
Epoch 34 loss 0.0619
Epoch 35 loss 0.0529
Epoch 36 loss 0.0657
Epoch 37 loss 0.0441
Epoch 38 loss 0.0536
Epoch 39 loss 0.0517
Epoch 40 loss 0.162
Epoch 41 loss 0.0404
Epoch 42 loss 0.11
Epoch 43 loss 0.0454
Epoch 44 loss 0.0354
Epoch 45 loss 0.0371
Epoch 46 loss 0.0618
Epoch 47 loss 0.037
Epoch 48 loss

In [108]:
extracted_users_data = extract_users_data(train, users, products)
x, cat_x = prepare_data_for_predict(extracted_users_data)
x = torch.from_numpy(x.values).float()
cat_x = torch.from_numpy(cat_x.values).float()
some_net.eval()
out = some_net(x, cat_x).squeeze()
out = out.detach().numpy()
out


array([-1.40748918e-04, -1.29651219e-01,  3.86074483e-02,  2.44690403e-02,
       -5.41557148e-02,  9.12551582e-03, -5.31750545e-02, -8.77603889e-05,
        8.37105215e-02, -8.85215402e-03, -6.05908781e-03,  5.29798120e-02,
        7.99169242e-02, -3.48218903e-02, -3.72124389e-02,  4.34123389e-02,
        9.19361413e-03, -4.91650403e-03,  8.10480267e-02, -2.91662961e-02,
       -2.07629949e-02,  1.89868659e-02,  3.06598656e-02,  4.28770110e-03,
        3.07860449e-02,  2.13561952e-02, -2.88083479e-02, -2.59745121e-03,
       -2.86682621e-02,  4.71007824e-02,  4.65838201e-02,  5.57028167e-02,
        5.34032211e-02,  1.67883635e-02,  1.73509195e-02, -5.47188520e-03,
        4.05341797e-02,  1.18311867e-02, -1.36282742e-01,  4.24725339e-02,
        4.40408736e-02, -2.80948952e-02, -4.06921580e-02, -1.57551020e-02,
       -2.79619619e-02,  5.92394173e-03, -1.43192559e-02, -3.47548500e-02,
       -1.00555271e-03,  4.83135879e-02, -2.98112705e-02, -1.92128494e-02,
       -3.36863324e-02,  

In [109]:
out_array = {int(user_id): out[i] > 0.3 for i, user_id in enumerate(extracted_users_data["user_id"].to_list())}
out_array

{139: False,
 242: False,
 108: False,
 143: False,
 140: False,
 202: False,
 270: False,
 212: False,
 189: False,
 205: False,
 255: False,
 215: False,
 273: False,
 281: False,
 227: False,
 222: False,
 235: False,
 171: False,
 188: False,
 135: False,
 252: False,
 238: False,
 145: False,
 286: False,
 157: False,
 265: False,
 127: False,
 159: False,
 119: False,
 274: False,
 160: False,
 105: False,
 261: False,
 185: False,
 183: False,
 192: False,
 186: False,
 102: False,
 124: False,
 282: False,
 210: False,
 125: False,
 272: False,
 104: False,
 115: False,
 136: False,
 285: False,
 133: False,
 187: False,
 175: False,
 161: False,
 167: False,
 213: False,
 292: False,
 256: False,
 278: False,
 263: False,
 148: False,
 200: False,
 280: False,
 287: False,
 208: False,
 149: False,
 233: False,
 236: False,
 246: False,
 193: False,
 147: False,
 158: False,
 251: False,
 277: False,
 182: False,
 151: False,
 253: False,
 295: False,
 262: False,
 178: False,

In [110]:
targets.values

array([[102,   0],
       [103,   0],
       [104,   0],
       [105,   0],
       [106,   0],
       [107,   0],
       [108,   0],
       [109,   0],
       [110,   0],
       [111,   0],
       [112,   0],
       [113,   0],
       [114,   0],
       [115,   0],
       [116,   0],
       [117,   0],
       [118,   0],
       [119,   0],
       [120,   0],
       [121,   0],
       [122,   0],
       [123,   0],
       [124,   0],
       [125,   0],
       [126,   0],
       [127,   0],
       [128,   0],
       [129,   0],
       [130,   0],
       [131,   0],
       [132,   1],
       [133,   0],
       [134,   0],
       [135,   0],
       [136,   0],
       [137,   0],
       [138,   0],
       [139,   0],
       [140,   0],
       [141,   0],
       [142,   0],
       [143,   0],
       [144,   0],
       [145,   0],
       [146,   0],
       [147,   0],
       [148,   0],
       [149,   0],
       [150,   0],
       [151,   0],
       [152,   0],
       [153,   0],
       [154,

In [112]:
numerator = 0
for row in targets.values[:]:
    if row[1] == out_array[row[0]]:
        print(row[0])
        numerator += 1

102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
165
166
167
168
169
170
171
172
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
267
268
269
270
271
272
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301


In [113]:
numerator

194

In [114]:
some_net(x, cat_x).detach()

tensor([[-1.4075e-04],
        [-1.2965e-01],
        [ 3.8607e-02],
        [ 2.4469e-02],
        [-5.4156e-02],
        [ 9.1255e-03],
        [-5.3175e-02],
        [-8.7760e-05],
        [ 8.3711e-02],
        [-8.8522e-03],
        [-6.0591e-03],
        [ 5.2980e-02],
        [ 7.9917e-02],
        [-3.4822e-02],
        [-3.7212e-02],
        [ 4.3412e-02],
        [ 9.1936e-03],
        [-4.9165e-03],
        [ 8.1048e-02],
        [-2.9166e-02],
        [-2.0763e-02],
        [ 1.8987e-02],
        [ 3.0660e-02],
        [ 4.2877e-03],
        [ 3.0786e-02],
        [ 2.1356e-02],
        [-2.8808e-02],
        [-2.5975e-03],
        [-2.8668e-02],
        [ 4.7101e-02],
        [ 4.6584e-02],
        [ 5.5703e-02],
        [ 5.3403e-02],
        [ 1.6788e-02],
        [ 1.7351e-02],
        [-5.4719e-03],
        [ 4.0534e-02],
        [ 1.1831e-02],
        [-1.3628e-01],
        [ 4.2473e-02],
        [ 4.4041e-02],
        [-2.8095e-02],
        [-4.0692e-02],
        [-1

In [115]:
roc(targets.expenses, some_net(x, cat_x).detach())

0.6383161512027491

In [12]:
torch.save(some_net.state_dict(), "../models/dummy_test")